{{- $mongodb_connection_string := print "mongodb://" .Values.mongodb.auth.username ":" .Values.mongodb.auth.password "@" .Values.db.hostname ":" .Values.db.port "/" .Values.mongodb.auth.database "?authSource=" .Values.mongodb.auth.database -}}
apiVersion: v1
kind: Secret
metadata:
  name: countly
  namespace: {{ .Release.Namespace }}
  labels:
    app: countly
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mongodb.auth }}
  countly_config__mongodb: {{ $mongodb_connection_string | b64enc | quote }}
  {{ end }}
  {{ if .Values.api.smtp.user }}
  countly_config__mail_config_auth_user: {{ .Values.api.smtp.user | b64enc | quote }} 
  {{ end }}
  {{ if .Values.api.smtp.password }}
  countly_config__mail_config_auth_pass: {{ .Values.api.smtp.password | b64enc | quote }} 
  {{ end }}